Repository TEAM-ISAID/ISAID, pull requests merged in 2025-06, with the labels that each got.

#5 Feat : 컴포넌트 1차 개발 #3
  app/globals.css
  app/layout.tsx
  app/page.tsx
  components.json
  components/bottom-bar/bottom-tab.tsx
  components/bottom-bar/index.tsx
  components/button.tsx
  components/input.tsx
  components/question-option.tsx
  components/tab.tsx
  components/ui/button.tsx
  lib/utils.ts
  next.config.ts
  package.json
  public/fonts/Pretendard/Pretendard-Black.woff
  public/fonts/Pretendard/Pretendard-Bold.woff
  public/fonts/Pretendard/Pretendard-ExtraBold.woff
  public/fonts/Pretendard/Pretendard-ExtraLight.woff
  public/fonts/Pretendard/Pretendard-Light.woff
  public/fonts/Pretendard/Pretendard-Medium.woff
  public/fonts/Pretendard/Pretendard-Regular.woff
  public/fonts/Pretendard/Pretendard-SemiBold.woff
  public/fonts/Pretendard/Pretendard-Thin.woff
  public/images/bottom-chart.tsx
  public/images/circle-check.tsx
  public/images/circle-empty.tsx
  public/images/home.tsx
  public/images/piggy-bank.tsx
  types/components.ts
Labels: style

#8 Setting : husky 설정 및 tailwind css 클래스 정렬, import 경로 정렬 설정 추가 #7
  .github/ISSUE_TEMPLATE/chore.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/pull_request_template.md
  .husky/commit-msg
  .husky/pre-commit
  .prettierrc
  app/(routes)/isa/_components/ISAPageContainer.tsx
  app/(routes)/isa/_components/TaxSavingCard.tsx
  app/(routes)/isa/calculate/page.tsx
  app/(routes)/isa/page.tsx
  app/globals.css
  commitlint.config.js
  components.json
  components/bottom-bar/bottom-tab.tsx
  components/bottom-bar/index.tsx
  components/button.tsx
  components/question-option.tsx
  components/ui/button.tsx
  eslint.config.mjs
  lib/utils.ts
  next.config.ts
  package.json
  postcss.config.mjs
  public/images/circle-check.tsx
  public/images/circle-empty.tsx
  tsconfig.json
  utils/taxSavingCaculate.ts
Labels: setting

#9 Feat : 헤더바 / 햄버거 메뉴 구현
  .github/workflows/ci.yml
  .gitignore
  .prettierrc
  app/(routes)/isa/_components/ISAPageContainer.tsx
  app/(routes)/isa/_components/TaxSavingCard.tsx
  app/(routes)/isa/_components/isa-page-container.tsx
  app/(routes)/isa/page.tsx
  app/(routes)/mypage/page.tsx
  app/globals.css
  app/layout.tsx
  components/header-bar/header-bar.tsx
  components/header-bar/main-header-bar.tsx
  components/header-bar/page-header.tsx
  components/header-bar/side-bar.tsx
  context/header-context.tsx
  package-lock.json
  package.json
  public/images/back-icon.tsx
  public/images/menu-icon.tsx
  public/images/sample-profile.png
  types/components.ts
Labels: feat

#19 Feat: ETF 페이지 구현
  app/(routes)/etf/_components/etf-page-container.tsx
  app/(routes)/etf/_components/slide-card.tsx
  app/(routes)/etf/_components/slider-wrapper.tsx
  app/(routes)/etf/category/[category-id]/_components/category-page-container.tsx
  app/(routes)/etf/category/[category-id]/_components/custom-select.tsx
  app/(routes)/etf/category/[category-id]/_components/etf-table.tsx
  app/(routes)/etf/category/[category-id]/_components/search-bar.tsx
  app/(routes)/etf/category/[category-id]/data/category-data.ts
  app/(routes)/etf/category/[category-id]/page.tsx
  app/(routes)/etf/detail/[etf-code]/_components/etf-detail-chart.tsx
  app/(routes)/etf/detail/[etf-code]/_components/etf-detail-container.tsx
  app/(routes)/etf/detail/[etf-code]/_components/etf-detail-ratio-chart.tsx
  app/(routes)/etf/detail/[etf-code]/_components/etf-detail-table.tsx
  app/(routes)/etf/detail/[etf-code]/_components/skeleton.tsx
  app/(routes)/etf/detail/[etf-code]/data/etf-detail-data.ts
  app/(routes)/etf/detail/[etf-code]/data/etf-detail-ratio-data.ts
  app/(routes)/etf/detail/[etf-code]/data/etf-price-data.ts
  app/(routes)/etf/detail/[etf-code]/page.tsx
  app/(routes)/etf/page.tsx
  app/(routes)/etf/test/_components/progress-bar.tsx
  app/(routes)/etf/test/_components/test-end-container.tsx
  app/(routes)/etf/test/_components/test-page-container.tsx
  app/(routes)/etf/test/_components/test-start-container.tsx
  app/(routes)/etf/test/page.tsx
  app/globals.css
  app/layout.tsx
  components/bottom-bar/index.tsx
  components/button.tsx
  components/question-option.tsx
  components/tab.tsx
  hooks/useDebounce.ts
  lib/utils.ts
  package-lock.json
  package.json
  public/images/arrow-cross.tsx
  public/images/arrow-icon.tsx
  public/images/etf-rate.svg
  public/images/etf-rate.tsx
  public/images/etf-slide.tsx
  public/images/star-boy-finger.svg
  public/images/star-boy-test.svg
  types/components.ts
Labels: feat

#35 feat: isa계좌 등록,조회,삭제 api (#31)
  app/api/isa/route.ts
Labels: feat

#38 Fix: isa api 요청 형태 수정 (#37)
  app/api/isa/route.ts
Labels: fix

#40 Feat: ISA 계좌 연결 기능 구현 (#30)
  README.md
  app/(routes)/isa/_components/isa-detail.tsx
  app/(routes)/mypage/account-connect/_components/account-connect-page-container.tsx
  app/(routes)/mypage/account-connect/_components/account-type-select.tsx
  app/(routes)/mypage/account-connect/_components/bank-select-sheet.tsx
  app/(routes)/mypage/account-connect/page.tsx
  app/(routes)/mypage/page.tsx
  app/api/isa/route.ts
  app/layout.tsx
  data/bank-data.ts
  lib/prisma.ts
  package-lock.json
  package.json
  public/file.svg
  public/globe.svg
  public/images/bank-icons/hanaIcon.svg
  public/images/bank-icons/ibkIcon.svg
  public/images/bank-icons/kIcon.svg
  public/images/bank-icons/kakaoIcon.svg
  public/images/bank-icons/kbIcon.svg
  public/images/bank-icons/nhIcon.svg
  public/images/bank-icons/scIcon.svg
  public/images/bank-icons/sinhanIcon.svg
  public/images/bank-icons/tossIcon.svg
  public/images/bank-icons/wooriIcon.svg
  public/images/common/arrow-down.svg
  public/images/my-page/service.svg
  public/images/securities-icons/hanaIcon.svg
  public/images/securities-icons/kbIcon.jpeg
  public/images/securities-icons/kiwoomIcon.png
  public/images/securities-icons/koreaIcon.png
  public/images/securities-icons/miraeIcon.png
  public/images/securities-icons/nhIcon.png
  public/images/securities-icons/samsungIcon.png
  public/images/securities-icons/sinhanIcon.png
  public/next.svg
  public/vercel.svg
  public/window.svg
Labels: feat

#46 feat: middleware.ts 설정 변경 및 세션 보유시 /main 이동 로직 추가 (#45)
  app/(routes)/(auth)/login/_components/login-form.tsx
  app/(routes)/(auth)/login/page.tsx
  app/(routes)/(auth)/register/page.tsx
  app/(routes)/isa/_components/isa-page-container.tsx
  app/(routes)/main/_components/main-page-container.tsx
  app/(routes)/main/page.tsx
  app/(routes)/mypage/page.tsx
  app/page.tsx
  components/bottom-bar/index.tsx
  components/header-bar/page-header.tsx
  components/main/main-container.tsx
  components/main/today-quiz.tsx
  middleware.ts
Labels: feat

#65 Fix: 스키마 변경 (#63)
  prisma/migrations/20250620011743_init/migration.sql
  prisma/schema.prisma
Labels: fix

#73 feat: user api pincode 추가, verify-pin api (#67)
  app/api/auth/join/route.ts
  app/api/user/me/route.ts
  app/api/user/update/route.ts
  app/api/user/verify-pin/route.ts
Labels: feat

#74 Feat: 루트 페이지 구현 (#66)
  app/(routes)/(auth)/layout.tsx
  app/layout.tsx
  app/page.tsx
  components/button.tsx
  components/root/body-wrapper.tsx
  components/root/root-page-container.tsx
Labels: feat

#84 feat: 퀴즈 api,캘린더 조회 (#79)
  app/api/quiz/calendar/route.ts
  app/api/quiz/question/route.ts
  app/api/quiz/question/submit/route.ts
  package-lock.json
  package.json
Labels: feat

#82 Feat: 퀴즈 복기 기능
  app/(routes)/main/_components/main-page-container.tsx
  app/(routes)/main/_components/quiz-banner.tsx
  app/(routes)/quiz/_components/quiz-content.tsx
  app/(routes)/quiz/_components/quiz-page-container.tsx
  app/(routes)/quiz/_components/result-page.tsx
  lib/utils.ts
Labels: feat

#87 Feat: Jest 환경 세팅 및 ETF risk & mbti test 단위 및 통합 테스트 작성 (#68)
  __mocks__/auth-options.ts
  __mocks__/next-auth.ts
  __mocks__/prisma-factory.ts
  __mocks__/prisma.ts
  __tests__/api/etf-test-api.test.ts
  __tests__/helpers/etf-test-helpers.ts
  __tests__/services/etf-test-service.test.ts
  app/api/etf/mbti/route.ts
  eslint.config.mjs
  jest.config.ts
  package-lock.json
  package.json
  services/etf/etf-test-service.ts
  tsconfig.json
Labels: enhancement

#89 Feat: 절세 계산 탭 구현 및 캘린더 거래내역 연동
  app/(routes)/isa/_components/calculate.tsx
  app/(routes)/isa/_components/calendar.tsx
  app/(routes)/isa/_components/contribution-limit.tsx
  app/(routes)/isa/_components/isa-detail.tsx
  app/(routes)/isa/_components/isa-page-container.tsx
  app/(routes)/isa/calculate/page.tsx
  app/(routes)/isa/page.tsx
  app/actions/get-trasactions.tsx
  app/actions/login.ts
  app/actions/tax-saving.tsx
  utils/taxSavingCaculate.ts
Labels: feat

#110 Feat: 계좌 연결 없는 경우 보이는 ISA 페이지 화면 구현
  app/(routes)/isa/_components/isa-page-container-when-hasnot.tsx
  app/(routes)/isa/page.tsx
  public/images/isa/feature-guide-character.svg
Labels: feat

#108 Feat: Quiz 페이즈 API 연동
  app/(routes)/main/_components/main-page-container.tsx
  app/(routes)/main/_components/quiz-banner.tsx
  app/(routes)/quiz/_components/quiz-content.tsx
  app/(routes)/quiz/_components/quiz-page-container.tsx
  app/(routes)/quiz/_components/result-page.tsx
  app/(routes)/quiz/page.tsx
  app/api/quiz/question/route.ts
  app/api/quiz/question/submit/route.ts
  public/images/Star_Pro_Quiz.svg
Labels: feat

#122 Feat: logout
  app/(routes)/mypage/profile/_components/profile-container.tsx
Labels: feat

#121 Feat 메인 페이지 수정
  app/(routes)/main/_components/main-page-container.tsx
  app/(routes)/main/_components/quiz-banner.tsx
  app/(routes)/main/_components/weekly-calendar.tsx
  app/(routes)/quiz/_components/result-page.tsx
  public/images/quiz/Star_Pro_Quiz.svg
  public/images/quiz/quiz-banner-character.svg
  public/images/quiz/quiz-banner-gift.svg
  public/images/quiz/quiz-trophy.svg
Labels: feat

#126 Fix: isa 탭에서 평가수익, 평가금액 반영 수정
  app/actions/get-monthly-returns.ts
Labels: bug

#130 Feat: Prisma UserChallengeProgress 중간 테이블 모델 작성 (#128)
  components/header-bar/header-bar.tsx
  components/root/body-wrapper.tsx
  prisma/migrations/20250624043135_add_user_challenge_progress/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: feat

#132 fix: 추천을 위해 탐색하는 etf 종목 개수 400으로 수정
  app/api/etf/recommend/route.ts
Labels: fix

#133 Feat: 챌린지 내용 가져오기 및 유저의 달성/미달성/수령완료 여부 렌더링
  app/(routes)/challenge/_components/challenge-page-container.tsx
  app/(routes)/challenge/_components/mission-item.tsx
  app/(routes)/challenge/data/challenge-list.tsx
  app/(routes)/challenge/page.tsx
  app/(routes)/isa/_components/account.tsx
  app/(routes)/main/_components/account-summary-card.tsx
  app/actions/get-challenge.ts
  public/images/isa/account-icon.tsx
Labels: feat

#140 Feat: tax 계산 로직 수정 및 탭 UI 수정 (#102)
  app/(routes)/isa/_components/calculate.tsx
  app/(routes)/isa/_components/isa-detail.tsx
  app/(routes)/isa/_components/portfolio.tsx
  app/(routes)/isa/page.tsx
  app/(routes)/mypage/_components/my-page-container.tsx
  app/(routes)/mypage/edit-profile/name/_components/edit-name-container.tsx
  app/actions/get-isa-portfolio.ts
  app/actions/get-monthly-returns.ts
  app/actions/tax-saving.tsx
  lib/data/general/general-holding-snapshot.ts
Labels: feat

#146 feat: 연속 출석 로직 수정(#144)
  app/(routes)/main/_components/main-page-container.tsx
  app/api/etf/recommend/route.ts
Labels: feat

#153 Feat: 챌린지 보상 수령 API 연동
  app/(routes)/challenge/_components/challenge-page-container.tsx
  app/(routes)/challenge/_components/mission-item.tsx
  app/(routes)/isa/_components/calculate.tsx
Labels: feat

#156 feat: 배당금 표시 분기 처리 추가 및 절세 리포트 아이콘/가치 추가
  app/(routes)/isa/_components/calculate.tsx
  app/(routes)/isa/_components/calendar.tsx
  app/(routes)/main/_components/account-summary-card.tsx
  app/(routes)/main/_components/main-page-container.tsx
  app/(routes)/main/page.tsx
  app/actions/get-trasactions.tsx
  public/images/isa/tax-report/baemin.svg
  public/images/isa/tax-report/chat-gpt.svg
  public/images/isa/tax-report/coupang.svg
  public/images/isa/tax-report/netflix.svg
  public/images/isa/tax-report/starbucks.svg
  public/images/isa/tax-report/youtube.svg
Labels: feat

#159 Feat: 페이지 헤더 및 간편 비밀번호 관련 UI, API 수정
  app/(routes)/mypage/edit-profile/pin/_components/edit-pin-container.tsx
  app/api/auth/join/route.ts
  app/api/user/update/route.ts
  app/api/user/verify-pin/route.ts
  components/header-bar/page-header.tsx
  prisma/migrations/20250625044510_modify_and_add_columns/migration.sql
  prisma/schema.prisma
Labels: feat, fix

#162 Fix: 계좌 보유 여부에 따라 메인화면 계좌정보 렌더링
  app/(routes)/main/page.tsx
Labels: bug

#168 feat: 보상동의 api
  app/api/user/reward-agree/route.ts
Labels: feat

#176 Feat: 가이드 내용 채우기
  app/(routes)/guide/data/article-data.ts
  app/(routes)/guide/data/category-data.ts
Labels: enhancement

#188 Feat: 공통 컴포넌트 Storybook 적용
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  components/header-bar/page-header.tsx
  components/header-bar/side-bar.tsx
  eslint.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  stories/common/Button.stories.tsx
  stories/common/bottom-bar.stories.tsx
  stories/common/bottom-tab.stories.tsx
  stories/common/input.stories.tsx
  stories/common/progress-bar.stories.tsx
  stories/common/secure-pincode-sheet.stories.tsx
  stories/common/tab.stories.tsx
  types/svg.d.ts
  vitest.config.ts
  vitest.shims.d.ts
Labels: enhancement

#189 Feat: ISA 리밸런싱 뷰 추가
  app/(routes)/guide/_components/guide-page-container.tsx
  app/(routes)/guide/articles/[id]/_components/article-page-container.tsx
  app/(routes)/guide/shorts-viewer/[category]/[id]/_components/shorts-viewer.tsx
  app/(routes)/guide/shorts-viewer/[category]/_components/shorts-viewer-container.tsx
  app/(routes)/isa/_components/isa-detail.tsx
  app/(routes)/isa/_components/isa-page-container.tsx
  app/(routes)/isa/_components/portfolio.tsx
  app/(routes)/quiz/_components/result-page.tsx
  app/api/isa/rebalancing/route.ts
  public/images/isa/star-pro-rebalancing-proper.svg
  public/images/isa/star-pro-rebalancing.svg
  types/isa.ts
Labels: feat

#196 feat: isa 서버액션 테스트 작성
  __tests__/services/get-isa-portfolio.test.ts
  __tests__/services/get-monthly-returns.test.ts
  app/actions/get-monthly-returns.ts
  app/api/challenge/claim/route.ts
Labels: enhancement

#201 Test: Challenge 리펙토링 및 테스트 작성 (#191)
  __mocks__/prisma-factory.ts
  __mocks__/prisma.ts
  __tests__/api/challenge-claim-api.test.ts
  __tests__/api/etf-portfolio-api.test.ts
  __tests__/services/challenge-claim.test.ts
  __tests__/services/challenge-status.test.ts
  app/actions/get-challenge.ts
  app/api/challenge/claim/route.ts
  services/challenge/challenge-claim.ts
  services/challenge/challenge-status.ts
  services/challenge/streakChallengeProgress.ts
  utils/date.ts
Labels: enhancement

#207 Fix: 반응형 이슈 수정
  __tests__/services/__snapshots__/get-isa-portfolio.test.ts.snap
  app/(routes)/challenge/data/challenge-list.tsx
  app/(routes)/challenge/page.tsx
  app/(routes)/isa/_components/calendar.tsx
  app/(routes)/isa/_components/portfolio.tsx
  app/(routes)/isa/_components/profit-report.tsx
  app/(routes)/isa/page.tsx
Labels: chore, fix
